// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseDatabase() {
  return window['go']['main']['App']['CloseDatabase']();
}

export function ConnectPostgres(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ConnectPostgres'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreatePostgresDatabase(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreatePostgresDatabase'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteSavedQuery(arg1) {
  return window['go']['main']['App']['DeleteSavedQuery'](arg1);
}

export function DisableLogging() {
  return window['go']['main']['App']['DisableLogging']();
}

export function EnableLogging() {
  return window['go']['main']['App']['EnableLogging']();
}

export function ExportCSV(arg1) {
  return window['go']['main']['App']['ExportCSV'](arg1);
}

export function GetDistinctValues(arg1) {
  return window['go']['main']['App']['GetDistinctValues'](arg1);
}

export function GetLoggingStatus() {
  return window['go']['main']['App']['GetLoggingStatus']();
}

export function GetMinMaxDate() {
  return window['go']['main']['App']['GetMinMaxDate']();
}

export function GetSavedQueries() {
  return window['go']['main']['App']['GetSavedQueries']();
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function GetTimelineHistogram(arg1) {
  return window['go']['main']['App']['GetTimelineHistogram'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportCSV() {
  return window['go']['main']['App']['ImportCSV']();
}

export function OpenDatabase() {
  return window['go']['main']['App']['OpenDatabase']();
}

export function PushToPostgres(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['PushToPostgres'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function QueryEvents(arg1) {
  return window['go']['main']['App']['QueryEvents'](arg1);
}

export function SaveQuery(arg1, arg2) {
  return window['go']['main']['App']['SaveQuery'](arg1, arg2);
}

export function SetLoggingPersist(arg1) {
  return window['go']['main']['App']['SetLoggingPersist'](arg1);
}

export function ToggleBookmark(arg1) {
  return window['go']['main']['App']['ToggleBookmark'](arg1);
}

export function UpdateEventFields(arg1, arg2) {
  return window['go']['main']['App']['UpdateEventFields'](arg1, arg2);
}
