// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseDatabase() {
  return window['go']['main']['App']['CloseDatabase']();
}

export function DeleteSavedQuery(arg1) {
  return window['go']['main']['App']['DeleteSavedQuery'](arg1);
}

export function ExportCSV(arg1) {
  return window['go']['main']['App']['ExportCSV'](arg1);
}

export function GetDistinctValues(arg1) {
  return window['go']['main']['App']['GetDistinctValues'](arg1);
}

export function GetMinMaxDate() {
  return window['go']['main']['App']['GetMinMaxDate']();
}

export function GetSavedQueries() {
  return window['go']['main']['App']['GetSavedQueries']();
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function GetTimelineHistogram(arg1) {
  return window['go']['main']['App']['GetTimelineHistogram'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportCSV() {
  return window['go']['main']['App']['ImportCSV']();
}

export function OpenDatabase() {
  return window['go']['main']['App']['OpenDatabase']();
}

export function QueryEvents(arg1) {
  return window['go']['main']['App']['QueryEvents'](arg1);
}

export function SaveQuery(arg1, arg2) {
  return window['go']['main']['App']['SaveQuery'](arg1, arg2);
}

export function ToggleBookmark(arg1) {
  return window['go']['main']['App']['ToggleBookmark'](arg1);
}

export function UpdateEventFields(arg1, arg2) {
  return window['go']['main']['App']['UpdateEventFields'](arg1, arg2);
}
