// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {database} from '../models';

export function CloseDatabase():Promise<void>;

export function DeleteSavedQuery(arg1:string):Promise<void>;

export function ExportCSV(arg1:main.QueryRequest):Promise<string>;

export function GetDistinctValues(arg1:string):Promise<Record<string, number>>;

export function GetMinMaxDate():Promise<Array<string>>;

export function GetSavedQueries():Promise<Array<database.SavedQuery>>;

export function GetTags():Promise<Array<string>>;

export function GetTimelineHistogram(arg1:main.QueryRequest):Promise<Array<main.TimelineBucket>>;

export function GetVersion():Promise<string>;

export function ImportCSV():Promise<main.DBInfo>;

export function OpenDatabase():Promise<main.DBInfo>;

export function QueryEvents(arg1:main.QueryRequest):Promise<main.QueryResponse>;

export function SaveQuery(arg1:string,arg2:string):Promise<void>;

export function ToggleBookmark(arg1:number):Promise<number>;

export function UpdateEventFields(arg1:number,arg2:Record<string, any>):Promise<void>;
